---
apiVersion: v1
kind: Service
metadata:
  name: chan-backend
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    app: chan-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chan-backend
spec:
  selector:
    matchLabels:
      app: chan-backend
  template:
    metadata:
      labels:
        app: chan-backend
    spec:
      containers:
        - name: chan-backend
          image: docker.io/how2die/chan-backend
          ports:
            - containerPort: 5000
              name: http-port
          volumeMounts:
          - name: chan-backend-folder
            mountPath: /var/chan
          env:
          - name: DB_HOST
            value: "postgres"
          - name: DB_PORT
            value: 5432
          - name: DB_NAME
            value: "chan"
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: password
          - name: AUTH_HOST
            value: "https://auth.how2die.com"
      volumes:
      - name: chan-backend-folder
        persistentVolumeClaim:
          claimName: chan-backend-pvc
